name: Deploy WordPress Theme con acción alternativa

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Subida por FTP (alternativa)
        uses: sebastianpopp/ftp-action@v1.2.0
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: ./
          remoteDir: /wp-content/themes/rcd-chilecalifornia/
