name: Deploy WordPress Theme por FTP

on:
  push:
    branches:
      - main  # Cambia a tu rama principal si es distinta

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Subir a la carpeta del theme en WordPress
        uses: SamKirkland/FTP-Deploy-Action@4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /wp-content/themes/rcd-chilecalifornia/

